[package]
name = "zlib-stream-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
thiserror = "1.0.28"
flate2 = { version = "1.0", features = ["tokio", "cloudflare_zlib"], default-features = false }